### ISSUE TITLE
SUGGESTION - Custom Application Options

### ISSUE THREAD

**Issue by hairyfred** [SMC242/CodingDND#1]
For example another situation where discord dnd would be usefull is steam vr
but instead of just adding indivudal applications is it possible for a drop down list of currently running programs

**Comment by SMC242** [comment]
This is planned for the next update :smile:

I wasn't sure how to make the UI for it and this is a great idea. Thanks!

**Comment by hairyfred** [comment]
you might be able to use the system rich presence uses BUT idk if thats possible

**Comment by SMC242** [comment]
That's very possible yes. It's easier and a bit more robust than using `tasklist`/`ps -aux`.

I decided to not do that for 2 reasons: 
- A user might not want others to know what they're doing (I.E something private)
- Apps aren't always added automatically to Discord and it can be awkward sometimes

**Comment by SMC242** [comment]
The feature is done
